name: Test UX/UI

on: [ push ]

jobs:
  test-container:
    runs-on: ubuntu-20.04
    container: simple-home/simplehome-container:dev
    env:
      APP_ENV: test
    services:
      database:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
    steps:
      - name: Clone platform
        uses: actions/checkout@v2

      - name: Install Shopware
        run: |
          composer install
          npx cypress run